### ISSUE TITLE
Checklist for enabling the CI on dlang organization

### ISSUE THREAD

**Issue by Dicebot** [MartinNowak/ci#7]
- [x] Move this repository to new "dlang/ci" repository
- [x] Adjust URLs to refer to "real" endpoints
- [x] Add `Jenkinsfile`s with trigger to all main `dlang` repos

**Comment by MartinNowak** [comment]
Only the owner (or so) can move the repo, I could sync dlang-test/ci and transfer that.

**Comment by wilzbach** [comment]
> Only the owner (or so) can move the repo, I could sync dlang-test/ci and transfer that.

AFAICT it should be possible for @Dicebot to do the the transfer to `dlang` (or at least to @MartinNowak)
See also: https://help.github.com/articles/about-repository-transfers/

> When the current owner initiates the transfer, the new owner will receive an email giving the option to accept or reject the transfer. If the new owner doesn't accept the transfer within one day, it won't complete.
>The target account must not have a repository with the same name, or a fork in the same network.
> The original owner of the repository is added as a collaborator on the transferred repository. Other collaborators to the transferred repository remain intact.

**Comment by MartinNowak** [comment]
I can't b/c I'm not the owner of _this_ repo, we need @Dicebot to do that.

**Comment by Dicebot** [comment]
Any reason why you want to move this one as opposed to `dlang-test/ci`? Latter is the one which actually participates in test job runs.

**Comment by Dicebot** [comment]
(I tried to transfer to you, but can't do that while fork with same name exists under your user name)

**Comment by MartinNowak** [comment]
We simply ended up using _this_ repo (see https://ci2.dawg.eu/), and it has all the issues as well.
Deleted my dlangci fork @Dicebot.

**Comment by Dicebot** [comment]
Initiated transfer. Sorry, I am quite out of loop now and not checking github notifications - please poke me via e-mail in case something is needed urgent'ish.
